/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0b1323",
        surface: "#0b1323",
        "surface-container": "#18202f",
        "surface-container-high": "#222a3a",
        "surface-container-lowest": "#060e1d",
        "surface-container-low": "#131c2b",
        "surface-container-highest": "#2d3546",
        "surface-variant": "#2d3546",
        "surface-bright": "#31394a",
        "surface-dim": "#0b1323",
        "on-background": "#dbe2f8",
        "on-surface": "#dbe2f8",
        "on-surface-variant": "#c3c6d7",
        primary: "#b4c5ff",
        "primary-container": "#2563eb",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary": "#002a78",
        "on-primary-container": "#eeefff",
        secondary: "#bec6e0",
        "secondary-container": "#3f465c",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary": "#283044",
        "on-secondary-container": "#adb4ce",
        tertiary: "#ffb59d",
        "tertiary-container": "#c2410c",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#ffb59d",
        "on-tertiary": "#5d1800",
        "on-tertiary-container": "#ffece7",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        outline: "#8d90a0",
        "outline-variant": "#434655",
        "inverse-surface": "#dbe2f8",
        "inverse-on-surface": "#283041",
        "inverse-primary": "#0053db",
        "surface-tint": "#b4c5ff",
        "electric-blue": "#3B82F6",
        "glow-cyan": "#06B6D4",
        "success-emerald": "#10B981",
        "midnight-slate": "#0F172A",
        "glass-white": "rgba(255, 255, 255, 0.05)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        "3xl": "2.5rem",
        "4xl": "2rem",
        full: "9999px",
      },
      fontFamily: {
        outfit: ["Outfit", "sans-serif"],
        jakarta: ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "20px",
        "margin-tablet": "40px",
        "margin-desktop": "80px",
        "gutter": "24px",
        "stack-sm": "24px",
        "stack-md": "48px",
        "stack-lg": "80px",
        "stack-xl": "120px",
      },
      fontSize: {
        "headline-xl": ["80px", { lineHeight: "88px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "headline-md": ["36px", { lineHeight: "44px", fontWeight: "600" }],
        "headline-sm": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
